### PR TITLE
Add missing entries for Odin

### LINKED ISSUE #8: Wingpanel missing from report a problem dialog
The Wingpanel is missing from report a problem dialog. Should probably be under Desktop Components?

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/65916240-wingpanel-missing-from-report-a-problem-dialog?utm_campaign=plugin&utm_content=tracker%2F60555484&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F60555484&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #43: Missing Dock from Desktop Components
## What Happened

 I went to file an issue against the Dock from Feedback and couldn't find it

## Expected Behavior

Dock shows up under Desktop Components

## Steps to Reproduce

1. Open Feedback
2. Click Desktop Components
3. Look for Dock

## Platform Information

Odin RC

### LINKED ISSUE #44: Welcome/Onboarding missing
## What Happened

I went to file an issue on Onboarding and it's not in Feedback

## Expected Behavior

Onboarding shows under Desktop Components → Welcome

## Steps to Reproduce

1. Open Feedback
2. Click Desktop Components
3. Look for Onboarding/Welcome

## Platform Information

Odin RC

---

We may have intentionally omitted it because it's not clear what "Welcome" means? But in that case I think the solution may be to add a second line from the AppData to make it more clear what each component is, because it's frustrating not being able to send feedback for seemingly random components.

### PR DESCRIPTION
**Pull request by danrabbit**
Fixes #8 
Fixes #44 
Fixes #43

Probably should double check for any other missing entries before merging

- [x] a11y indicator
- [x] onboarding under Desktop

### CODE REVIEW

**Comment by cassidyjames** [comment]
@danrabbit there's also #8 if we wanted to hit it at the same time, otherwise I'm fine getting this merged in.

**Review by cassidyjames — APPROVED** [review]

**Comment by danrabbit** [comment]
@cassidyjames the discussion on #8 makes it sound like we decided not to add the panel intentionally

**Comment by cassidyjames** [comment]
@danrabbit ah okay. It was unclear because I thought the Panel would show back up when showing compulsory components.

**Comment by danrabbit** [comment]
Ah yeah, I suppose it would. We can add the panel in here :)

**Comment by cassidyjames** [comment]
@danrabbit a11y indicator also appears to be missing

**Comment by cassidyjames** [comment]
@danrabbit my only other question is if Welcome belongs with apps or with Desktop Components. I think of it as the later, but it's not super cut and dry.

**Comment by danrabbit** [comment]
Yeah that's a good point. Onboarding should probably be desktop since it's not really strictly an app. Do we have capnet under desktop as well?

**Review by cassidyjames — APPROVED** [review]

**Pull request merged**
