### PR TITLE
Read Appdata From Installed Flatpak Apps

### PR DESCRIPTION
**Pull request by Marukesu**
Since some default apps are now using flatpak, they stopped to appear here. This PR fix that. It still doesn't fix epiphany not showing though.

also, this update the screenshot RDNN, change the flatpak runtime to daily, and remove some useless binaries from the sandbox.

### CODE REVIEW

**Review by danrabbit — CHANGES_REQUESTED** [review]
I can confirm this brings back flatpak apps, but it looks like we lose icons for apps that are using system icons like Files and Terminal

**Comment by Marukesu** [comment]
> but it looks like we lose icons for apps that are using system icons like Files and Terminal

that was because #35, we need to add the [Icon tag](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#rag-icon) to the needed applications appdata.

**Comment by danrabbit** [comment]
It looks like it's still working in master here:

Screenshot from 2021-06-15 17 56 53

**Comment by Marukesu** [comment]
So i looked the appstream code, and it seems that they merge the .desktop data intro the components added by `AppStream.PoolFlags.READ_METAINFO`,  setting the icons property on them. I reverted the PR to do that.

However, that don't work for flatpaks, or inside the flatpak sandbox, since the desktop and metainfo files isn't on `/usr/share/applications` and `/usr/share/metainfo`.

**Review by danrabbit — APPROVED** [review]

**Pull request merged**
