### PR TITLE
Wrap labels, disallow hscroll, expand listbox

### PR DESCRIPTION
**Pull request by danirabbit**
Makes it so the window can basically be the width of the buttons

Screenshot from 2022-12-16 12 21 42

### CODE REVIEW

**Review by lenemter — CHANGES_REQUESTED** [review]
I don't think it's supposed to look like this

image

**Comment by lenemter** [comment]
IMO that "Desktop Components" label should be fully centered like this

image

**Comment by danirabbit** [comment]
@lenemter thanks for thorough testing! Both of those should now be fixed :)

**Review by lenemter — APPROVED** [review]
Looks good. Nice work

**Pull request merged**
